name: Update Solana Validators CSV

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Create .env file
        run: echo "IPINFO_API_KEY=${{ secrets.IPINFO_API_KEY }}" > .env

      - name: Run Deno script
        run: deno run --env-file=.env -A ./main.ts

      - name: Commit and push changes
        id: commit
        run: |
          git pull
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          echo "{\"timestamp\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > last_update.json
          git add solana_validators.csv last_update.json
          if git commit -m "⚙️ Update solana_validators.csv"; then
            tag_name="date-$(date -u +%Y-%m-%d)"
            if ! git tag -l | grep -q "^$tag_name$"; then
              git tag $tag_name
              git push origin ${{ github.ref_name }}
              git push origin $tag_name
              echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
              echo "create_release=true" >> $GITHUB_OUTPUT
            else
              echo "Tag already exists, skipping release"
              echo "create_release=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No changes to commit"
            echo "create_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload CSV to Release
        if: steps.commit.outputs.create_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: solana_validators.csv
          tag_name: ${{ steps.commit.outputs.tag_name }}
          name: Daily CSV Update ${{ steps.commit.outputs.tag_name }}
          body: "Automated update `solana_validators.csv` file: ${{ steps.commit.outputs.tag_name }}"
          make_latest: true